import { Activity } from "../types/activity";

export const mockActivities: Activity[] = [
  {
    id: "1",
    name: "Circuito de estaciones",
    classMoment: "desarrollo",
    primaryObjective: "Desarrollar la resistencia aeróbica mediante ejercicios variados en estaciones",
    secondaryObjective: "Fomentar el trabajo en equipo y la rotación ordenada",
    physicalCapacity: "resistencia",
    minParticipants: 8,
    maxParticipants: 40,
    suggestedGrades: ["5°", "6°", "7°", "8°"],
    durationMinutes: 20,
    intensity: "alta",
    space: "gimnasio",
    equipment: ["conos", "cuerdas", "colchonetas", "cronometro", "silbato"],
    description: "Los estudiantes rotan por 5 estaciones de 3 minutos cada una: saltos de cuerda, abdominales en colchoneta, skipping en escalera, desplazamientos laterales entre conos y plancha isométrica. 1 minuto de descanso entre estaciones.",
    organization: "Grupos de 5 a 8 estudiantes por estación. Rotación en sentido horario al sonido del silbato.",
    variants: ["Aumentar tiempo por estación a 4 min", "Reducir a 3 estaciones para cursos menores", "Agregar estación de trote estacionario"],
    safetyNotes: "Verificar que las colchonetas estén bien colocadas. Hidratación cada 2 estaciones.",
    observationCriteria: ["Mantiene ritmo constante durante toda la actividad", "Ejecuta correctamente cada ejercicio", "Respeta los tiempos de rotación"],
    tags: ["circuito", "resistencia", "estaciones", "trabajo en equipo"],
    isFavorite: false,
    createdAt: "2025-03-10T08:00:00Z",
    updatedAt: "2025-03-10T08:00:00Z",
  },
  {
    id: "2",
    name: "Carrera de relevos por equipos",
    classMoment: "desarrollo",
    primaryObjective: "Mejorar la resistencia cardiovascular a través de relevos continuos",
    secondaryObjective: "Desarrollar el sentido de pertenencia al equipo",
    physicalCapacity: "resistencia",
    minParticipants: 12,
    maxParticipants: 36,
    suggestedGrades: ["7°", "8°", "I", "II"],
    durationMinutes: 15,
    intensity: "alta",
    space: "cancha_grande",
    equipment: ["conos", "bastones", "petos", "silbato"],
    description: "Equipos de 4 a 6 estudiantes realizan relevos en circuito de 200m. Cada estudiante completa 3 vueltas pasando el bastón al compañero. Gana el equipo que complete primero todas las vueltas sin soltar el bastón.",
    organization: "Formar equipos equilibrados. Delimitar zona de intercambio con conos. Cada equipo usa petos de un color.",
    variants: ["Relevos con obstáculos (vallas bajas)", "Relevos transportando balón", "Relevos en parejas"],
    safetyNotes: "Calentamiento previo de 5 minutos. Superficie libre de obstáculos. No correr con el bastón en la boca.",
    observationCriteria: ["Entrega correcta del bastón en zona de intercambio", "Mantiene velocidad constante", "Anima a sus compañeros"],
    tags: ["relevos", "resistencia", "carrera", "equipo"],
    isFavorite: true,
    createdAt: "2025-03-12T10:30:00Z",
    updatedAt: "2025-04-01T14:00:00Z",
  },
  {
    id: "3",
    name: "Persecución por parejas",
    classMoment: "desarrollo",
    primaryObjective: "Desarrollar la velocidad de reacción y desplazamiento en espacios reducidos",
    physicalCapacity: "velocidad",
    minParticipants: 10,
    maxParticipants: 30,
    suggestedGrades: ["3°", "4°", "5°", "6°"],
    durationMinutes: 10,
    intensity: "alta",
    space: "multicancha",
    equipment: ["conos", "silbato"],
    description: "Los estudiantes forman parejas. Uno persigue al otro dentro de un cuadrado delimitado por conos. Al silbato, cambian de rol. Cada ronda dura 30 segundos. Se alternan 6 rondas.",
    organization: "Delimitar cuadrados de 5x5m con conos. 2 parejas por cuadrado. Alternar parejas cada 3 rondas.",
    variants: ["Persecución a la pata coja", "Persecución en cuadrupedia", "El perseguidor usa peto para identificar"],
    safetyNotes: "Mantener distancia entre cuadrados. Prohibido empujar. Usar zapatillas adecuadas.",
    observationCriteria: ["Cambia de dirección rápidamente", "Anticipa movimientos del compañero", "Mantiene intensidad durante todas las rondas"],
    tags: ["velocidad", "reacción", "parejas", "juego"],
    isFavorite: false,
    createdAt: "2025-03-15T09:00:00Z",
    updatedAt: "2025-03-15T09:00:00Z",
  },
  {
    id: "4",
    name: "Simón dice en movimiento",
    classMoment: "calentamiento",
    primaryObjective: "Activar el sistema neuromuscular y mejorar la velocidad de reacción",
    secondaryObjective: "Mejorar la atención y la escucha activa",
    physicalCapacity: "reaccion",
    minParticipants: 6,
    maxParticipants: 40,
    suggestedGrades: ["1°", "2°", "3°", "4°"],
    durationMinutes: 8,
    intensity: "media",
    space: "sala",
    equipment: ["silbato"],
    description: "El profesor da instrucciones precedidas por 'Simón dice'. Los estudiantes ejecutan movimientos como saltar, agacharse, girar o correr en el lugar. Si la instrucción no lleva 'Simón dice', no deben moverse. Quien se equivoque hace 3 saltos de rana.",
    organization: "Estudiantes dispersos por el espacio con brazos extendidos de distancia entre ellos. Profesor al frente visible para todos.",
    variants: ["Con música de fondo", "Instrucciones visuales con tarjetas", "Líder estudiantil rotativo"],
    safetyNotes: "Espacio despejado de mesas y sillas. Distancia mínima de 1 metro entre estudiantes.",
    observationCriteria: ["Reacciona en menos de 1 segundo", "Discrimina correctamente instrucciones válidas", "Ejecuta el movimiento con técnica adecuada"],
    tags: ["reacción", "calentamiento", "juego", "atención"],
    isFavorite: true,
    createdAt: "2025-02-20T11:00:00Z",
    updatedAt: "2025-04-05T08:30:00Z",
  },
  {
    id: "5",
    name: "El espejo",
    classMoment: "cierre",
    primaryObjective: "Mejorar la flexibilidad general mediante estiramientos guiados",
    secondaryObjective: "Promover la conciencia corporal y la relajación",
    physicalCapacity: "flexibilidad",
    minParticipants: 2,
    maxParticipants: 40,
    suggestedGrades: ["1°", "2°", "3°", "4°", "5°", "6°"],
    durationMinutes: 10,
    intensity: "baja",
    space: "sala",
    equipment: ["colchonetas"],
    description: "Por parejas, un estudiante realiza un estiramiento y el compañero lo imita como un espejo. El profesor guía los grupos musculares: cuello, hombros, brazos, tronco, piernas. Se alternan roles cada 30 segundos. Se finaliza con respiración consciente en posición acostada.",
    organization: "Parejas frente a frente sobre colchonetas. Distribución uniforme por el espacio.",
    variants: ["Estiramientos con música suave", "Secuencia guiada solo por el profesor", "Incorporar ejercicios de respiración guiada"],
    safetyNotes: "Movimientos suaves, sin rebotes. No forzar articulaciones. Respetar el límite de cada estudiante.",
    observationCriteria: ["Mantiene postura correcta durante el estiramiento", "Respeta el ritmo del compañero", "Logra relajación visible al final de la actividad"],
    tags: ["flexibilidad", "cierre", "vuelta a la calma", "relajación"],
    isFavorite: false,
    createdAt: "2025-01-15T14:00:00Z",
    updatedAt: "2025-01-15T14:00:00Z",
  },
  {
    id: "6",
    name: "Malabares con pelotas",
    classMoment: "desarrollo",
    primaryObjective: "Desarrollar la coordinación óculo-manual mediante ejercicios progresivos de malabares",
    secondaryObjective: "Fomentar la perseverancia y la concentración",
    physicalCapacity: "coordinacion",
    minParticipants: 4,
    maxParticipants: 30,
    suggestedGrades: ["5°", "6°", "7°", "8°"],
    durationMinutes: 15,
    intensity: "media",
    space: "patio_pequeno",
    equipment: ["pelotas_tenis", "conos"],
    description: "Progresión de malabares: lanzar y atrapar 1 pelota con mano dominante, luego con ambas manos alternadas, luego 2 pelotas en cascada. Cada estudiante practica a su ritmo. Se forman grupos para compartir avances. Al final, demostración voluntaria.",
    organization: "Estudiantes en semicírculo con 2 metros de distancia entre ellos. Conos marcan la posición individual.",
    variants: ["Usar pañuelos para caída más lenta", "Malabares por parejas lanzándose mutuamente", "Agregar desplazamiento lateral mientras se lanza"],
    safetyNotes: "Usar pelotas de tenis, no pelotas duras. Mirar la trayectoria en todo momento. Recoger pelotas caídas para evitar tropiezos.",
    observationCriteria: ["Sigue la trayectoria de la pelota con la mirada", "Coordina lanzamiento y recepción sin perder el control", "Muestra progreso individual respecto al inicio de la clase"],
    tags: ["coordinación", "malabares", "óculo-manual", "progresión"],
    isFavorite: false,
    createdAt: "2025-04-02T16:00:00Z",
    updatedAt: "2025-04-02T16:00:00Z",
  },
];
